--See disclaimer in Template:VoidLock.
--Feel free to use the Talk page for any issues.
--'IsVaulted = 1' denotes relics that have been Vaulted, duh.
--Replace it with 'IsBaro = 1' for relics being brought by our favourite Void merchant.

--Last update: June 19, 2018 - Limbo Prime Access
--翻譯by鋼砲

local VoidData = {
["Relics"] = {
    { Tier = "古紀", Name = "A1", 
        Drops = { {Item = "布萊頓", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "瓦斯托", Part = "槍機", Rarity = "常見"}, 
                  {Item = "SARYN", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "守望者", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "史提托雙槍", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "A2", 
        Drops = { {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "VALKYR", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "西諾斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "史提托雙槍", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "B1", 
        Drops = { {Item = "MAG", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "甲龍雙拳", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "RHINO", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "螺釘步槍", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "野豬", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "B2", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍托", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "歐特魯斯", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "布里斯提卡", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "B3", 
        Drops = { {Item = "伯斯頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "LIMBO", Part = "系統", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "弓弦", Rarity = "罕見"}, 
                  {Item = "歐特魯斯", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "布里斯提卡", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "古紀", Name = "C1", 
        Drops = { {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "NOVA", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "NOVA", Part = "系統", Rarity = "常見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈帶", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "搬運者", Part = "頭部", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "C2", 
        Drops = { {Item = "野馬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "凱旋之爪", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "螺釘雙槍", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "海波斯庫拉對劍", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "西諾斯", Part = "下弓臂", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "古紀", Name = "F1", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "分裂斬斧", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "ODONATA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "重擊巨錘", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "F2", 
        Drops = { {Item = "ODONATA", Part = "系統", Rarity = "常見"}, 
                  {Item = "飛揚", Part = "星鏢", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "狼牙", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "G1", 
        Drops = { {Item = "拉特昂", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FROST", Part = "機體", Rarity = "常見"}, 
                  {Item = "收割者", Part = "握柄", Rarity = "常見"}, 
                  {Item = "EMBER", Part = "系統", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "戰刃", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "G2", 
        Drops = { {Item = "玻之武杖", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "拉特昂", Part = "槍托", Rarity = "常見"}, 
                  {Item = "蛟龍", Part = "頭部", Rarity = "常見"}, 
                  {Item = "FROST", Part = "系統", Rarity = "罕見"}, 
                  {Item = "LOKI", Part = "機體", Rarity = "罕見"}, 
                  {Item = "戰刃", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "H1", 
        Drops = { {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "SARYN", Part = "系統", Rarity = "常見"}, 
                  {Item = "史提托雙槍", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "海波斯庫拉對劍", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "頭部", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "H2", 
        Drops = { {Item = "ZEPHYR", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "歐特魯斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "OBERON", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "頭部", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "古紀", Name = "K1", 
        Drops = { {Item = "狼牙", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "ODONATA", Part = "外甲", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "TRINITY", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈扣", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "M1", 
        Drops = { {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "野豬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "月神", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "達克拉", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "MAG", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "N1", 
        Drops = { {Item = "NEKROS", Part = "機體", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "NOVA", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "N2", 
        Drops = { {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "旋刃飛刀", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "搬運者", Part = "系統", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈帶", Rarity = "罕見"}, 
                  {Item = "NEKROS", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "N3", 
        Drops = { {Item = "席芭莉絲", Part = "槍托", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍機", Rarity = "常見"}, 
                  {Item = "VALKYR", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "NEKROS", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "P1", 
        Drops = { {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "外殼", Rarity = "常見"}, 
                  {Item = "席芭莉絲", Part = "槍托", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "食人魚", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "古紀", Name = "S1", 
        Drops = { {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "飛揚", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓身", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "旋刃飛刀", Part = "鏢袋", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "S2", 
        Drops = { {Item = "搬運者", Part = "系統", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "NYX", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈帶", Rarity = "罕見"}, 
                  {Item = "月神", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "S3", 
        Drops = { {Item = "搬運者", Part = "系統", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "ASH", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "月神", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "旋刃飛刀", Part = "鏢袋", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "S4", 
        Drops = { {Item = "雷克斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "機體", Rarity = "罕見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈藍圖", Rarity = "罕見"}, 
                  {Item = "SARYN", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "S5", 
        Drops = { {Item = "搬運者", Part = "外殼", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍機", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "迦倫提恩", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "旋刃飛刀", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "S6", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "雙短柄戰鐮", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈帶", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "旋刃飛刀", Part = "鏢袋", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "S7", 
        Drops = { {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "MIRAGE", Part = "機體", Rarity = "常見"}, 
                  {Item = "螺釘雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "帕里斯", Part = "弓身", Rarity = "罕見"}, 
                  {Item = "席芭莉絲", Part = "槍管", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "T1", 
        Drops = { {Item = "野馬雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "布里斯提卡", Part = "下弓臂", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "T2", 
        Drops = { {Item = "布萊頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "席瓦＆神盾", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "狂鯊", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "古紀", Name = "V1", 
        Drops = { {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "VOLT", Part = "系統", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "重擊巨錘", Part = "握柄", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "V2", 
        Drops = { {Item = "狼牙", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "V3", 
        Drops = { {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "系統", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "V4", 
        Drops = { {Item = "旋刃飛刀", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "NEKROS", Part = "機體", Rarity = "常見"}, 
                  {Item = "凱旋之爪", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "古紀", Name = "V5", 
        Drops = { {Item = "野馬雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "BANSHEE", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "螺釘雙槍", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "布里斯提卡", Part = "下弓臂", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "古紀", Name = "Z1", 
        Drops = { {Item = "狼牙", Part = "握柄", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "MIRAGE", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "西諾斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "ZEPHYR", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "前紀", Name = "B1", 
        Drops = { {Item = "達克拉", Part = "握柄", Rarity = "常見"}, 
                  {Item = "歐特魯斯", Part = "握柄", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "MAG", Part = "機體", Rarity = "罕見"}, 
                  {Item = "歐特魯斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "野豬", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 1},
{ Tier = "前紀", Name = "B2", 
        Drops = { {Item = "OBERON", Part = "機體", Rarity = "常見"}, 
                  {Item = "席瓦＆神盾", Part = "握柄", Rarity = "常見"}, 
                  {Item = "VALKYR", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "HYDROID", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "皇家拐刃", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "BANSHEE", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "前紀", Name = "C1", 
        Drops = { {Item = "NOVA", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "SARYN", Part = "系統", Rarity = "常見"}, 
                  {Item = "分裂斬斧", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "ASH", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "搬運者", Part = "頭部", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "C2", 
        Drops = { {Item = "西諾斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "VALKYR", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "ODONATA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "搬運者", Part = "頭部", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "C3", 
        Drops = { {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "海波斯庫拉對劍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "SARYN", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "西諾斯", Part = "下弓臂", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "D1", 
        Drops = { {Item = "歐特魯斯", Part = "握柄", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "歐特魯斯", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "雙短柄戰鐮", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "D2", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "系統", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "技巧之劍", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "前紀", Name = "E1", 
        Drops = { {Item = "玻之武杖", Part = "ORNAMENT", Rarity = "常見"}, 
                  {Item = "FROST", Part = "機體", Rarity = "常見"}, 
                  {Item = "拉特昂", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "蛟龍", Part = "系統", Rarity = "罕見"}, 
                  {Item = "EMBER", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "F1", 
        Drops = { {Item = "野馬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "SARYN", Part = "系統", Rarity = "常見"}, 
                  {Item = "NEKROS", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "雙短柄戰鐮", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "重擊巨錘", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "F2", 
        Drops = { {Item = "拉特昂", Part = "槍托", Rarity = "常見"}, 
                  {Item = "EMBER", Part = "機體", Rarity = "常見"}, 
                  {Item = "暗殺者", Part = "槍管", Rarity = "常見"}, 
                  {Item = "收割者", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "FROST", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "F3", 
        Drops = { {Item = "EMBER", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "LOKI", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "收割者", Part = "握柄", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "戰刃", Part = "圓盤", Rarity = "罕見"}, 
                  {Item = "FROST", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "G1", 
        Drops = { {Item = "布萊頓", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "凱旋之爪", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "布里斯提卡", Part = "弓弦", Rarity = "罕見"}, 
                  {Item = "席瓦＆神盾", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "迦倫提恩", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "H1", 
        Drops = { {Item = "HYDROID", Part = "機體", Rarity = "常見"}, 
                  {Item = "MIRAGE", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "重擊巨錘", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "OBERON", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "頭部", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "K1", 
        Drops = { {Item = "西諾斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "NEKROS", Part = "機體", Rarity = "常見"}, 
                  {Item = "歐特魯斯", Part = "握柄", Rarity = "常見"}, 
                  {Item = "史提托雙槍", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "科加基", Part = "拳套", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "M1", 
        Drops = { {Item = "達克拉", Part = "握柄", Rarity = "常見"}, 
                  {Item = "螺釘步槍", Part = "槍管", Rarity = "常見"}, 
                  {Item = "甲龍雙拳", Part = "拳套", Rarity = "常見"}, 
                  {Item = "野豬", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "RHINO", Part = "機體", Rarity = "罕見"}, 
                  {Item = "MAG", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "N1", 
        Drops = { {Item = "狼牙", Part = "握柄", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "雙短柄戰鐮", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "NYX", Part = "頭部神經光元", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "N2", 
        Drops = { {Item = "飛揚", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "握柄", Rarity = "常見"}, 
                  {Item = "ASH", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "頭部神經光元", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "N3", 
        Drops = { {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍管", Rarity = "常見"}, 
                  {Item = "悅音", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "搬運者", Part = "頭部", Rarity = "罕見"}, 
                  {Item = "NEKROS", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "N4", 
        Drops = { {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "SARYN", Part = "系統", Rarity = "常見"}, 
                  {Item = "歐特魯斯", Part = "握柄", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "OBERON", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "N5", 
        Drops = { {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "HYDROID", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "NEKROS", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "O1", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "史提托雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "西諾斯", Part = "弓弦", Rarity = "罕見"}, 
                  {Item = "OBERON", Part = "頭部神經光元", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "O2",
        Drops = { {Item = "狂鯊", Part = "槍機", Rarity = "常見"},
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"},
                  {Item = "西諾斯", Part = "下弓臂", Rarity = "常見"},
                  {Item = "MIRAGE", Part = "系統", Rarity = "罕見"},
                  {Item = "野馬雙槍", Part = "連接器", Rarity = "罕見"},
                  {Item = "OBERON", Part = "頭部神經光元", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "前紀", Name = "S1", 
        Drops = { {Item = "NOVA", Part = "系統", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍托", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "罕見"}, 
                  {Item = "ODONATA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "月神", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "S2", 
        Drops = { {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓身", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "SARYN", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "S3", 
        Drops = { {Item = "VALKYR", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "NEKROS", Part = "機體", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "ASH", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "旋刃飛刀", Part = "鏢袋", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "S4", 
        Drops = { {Item = "狼牙", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "BANSHEE", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "TRINITY", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "SARYN", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "S5", 
        Drops = { {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍管", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "SARYN", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "席芭莉絲", Part = "槍管", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "S6", 
        Drops = { {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "外殼", Rarity = "常見"}, 
                  {Item = "VALKYR", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "弓弦", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "旋刃飛刀", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "S7", 
        Drops = { {Item = "西諾斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "凱旋之爪", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "海波斯庫拉對劍", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "帕里斯", Part = "弓身", Rarity = "罕見"}, 
                  {Item = "席芭莉絲", Part = "槍管", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "前紀", Name = "T1", 
        Drops = { {Item = "狼牙", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍機", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "狂鯊", Part = "槍管", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "前紀", Name = "T2", 
        Drops = { {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "BANSHEE", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "狂鯊", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "V1", 
        Drops = { {Item = "伯斯頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "旋刃飛刀", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "搬運者", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "守望者", Part = "槍機", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "V2", 
        Drops = { {Item = "瓦斯托", Part = "槍機", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "ASH", Part = "機體", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VOLT", Part = "機體", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "V3", 
        Drops = { {Item = "搬運者", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "旋刃飛刀", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈帶", Rarity = "罕見"}, 
                  {Item = "VOLT", Part = "機體", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "V4", 
        Drops = { {Item = "搬運者", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "VALKYR", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "ASH", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "V5", 
        Drops = { {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "弓身", Rarity = "常見"}, 
                  {Item = "旋刃飛刀", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "悅音", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "席瓦＆神盾", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "凱旋之爪", Part = "拳套", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "前紀", Name = "Z1", 
        Drops = { {Item = "伯斯頓", Part = "槍機", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "LIMBO", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "ZEPHYR", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "中紀", Name = "A1", 
        Drops = { {Item = "搬運者", Part = "系統", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "弓弦", Rarity = "罕見"}, 
                  {Item = "守望者", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "史提托雙槍", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "B1", 
        Drops = { {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "系統", Rarity = "常見"}, 
                  {Item = "野馬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "守望者", Part = "槍托", Rarity = "罕見"}, 
                  {Item = "伯斯頓", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "BANSHEE", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "B2", 
        Drops = { {Item = "猛虎", Part = "槍托", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "凱旋之爪", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "BANSHEE", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "B3", 
        Drops = { {Item = "野豬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "RHINO", Part = "系統", Rarity = "常見"}, 
                  {Item = "MAG", Part = "機體", Rarity = "罕見"}, 
                  {Item = "達克拉", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "螺釘步槍", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "B4", 
        Drops = { {Item = "HYDROID", Part = "機體", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "皇家拐刃", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "BANSHEE", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "B5", 
        Drops = { {Item = "布里斯提卡", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "技巧之劍", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "OBERON", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "BANSHEE", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "中紀", Name = "D1", 
        Drops = { {Item = "MAG", Part = "系統", Rarity = "常見"}, 
                  {Item = "瓦斯托", Part = "槍管", Rarity = "常見"}, 
                  {Item = "野豬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "達克拉", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "E1", 
        Drops = { {Item = "FROST", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "LOKI", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "蛟龍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "收割者", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "EMBER", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "F1", 
        Drops = { {Item = "EMBER", Part = "機體", Rarity = "常見"}, 
                  {Item = "暗殺者", Part = "槍管", Rarity = "常見"}, 
                  {Item = "暗殺者", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "玻之武杖", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "FROST", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "H1", 
        Drops = { {Item = "伯斯頓", Part = "槍機", Rarity = "常見"}, 
                  {Item = "重擊巨錘", Part = "錘頭", Rarity = "常見"}, 
                  {Item = "歐特魯斯", Part = "握柄", Rarity = "常見"}, 
                  {Item = "BANSHEE", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "HYDROID", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "K1", 
        Drops = { {Item = "悅音", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "席瓦＆神盾", Part = "握柄", Rarity = "常見"}, 
                  {Item = "VALKYR", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "ZEPHYR", Part = "機體", Rarity = "罕見"}, 
                  {Item = "科加基", Part = "拳套", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "中紀", Name = "L1", 
        Drops = { {Item = "悅音", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "皇家拐刃", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "MIRAGE", Part = "機體", Rarity = "常見"}, 
                  {Item = "布里斯提卡", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "席瓦＆神盾", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "LIMBO", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "中紀", Name = "M1", 
        Drops = { {Item = "螺釘雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "悅音", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "MIRAGE", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "中紀", Name = "N1", 
        Drops = { {Item = "飛揚", Part = "星鏢", Rarity = "常見"}, 
                  {Item = "守望者", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "月神", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈藍圖", Rarity = "罕見"}, 
                  {Item = "NYX", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "N2", 
        Drops = { {Item = "雷克斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "瓦斯托", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "NOVA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "N3", 
        Drops = { {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "ODONATA", Part = "系統", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "ASH", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "NEKROS", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "N4", 
        Drops = { {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "ASH", Part = "機體", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "凱旋之爪", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "N5", 
        Drops = { {Item = "SARYN", Part = "系統", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "外殼", Rarity = "常見"}, 
                  {Item = "ASH", Part = "系統", Rarity = "罕見"}, 
                  {Item = "史提托雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "N6", 
        Drops = { {Item = "野馬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "席芭莉絲", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "TRINITY", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "握柄", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "N7", 
        Drops = { {Item = "TRINITY", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "悅音", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "凱旋之爪", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "BANSHEE", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "NEKROS", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "N8", 
        Drops = { {Item = "HYDROID", Part = "機體", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "席芭莉絲", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "螺釘雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "海波斯庫拉對劍", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "中紀", Name = "O1", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "ODONATA", Part = "外甲", Rarity = "常見"}, 
                  {Item = "VOLT", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VOLT", Part = "系統", Rarity = "罕見"}, 
                  {Item = "ODONATA", Part = "機翼藍圖", Rarity = "稀有"}},
        IsBaro = 1},
    { Tier = "中紀", Name = "S1", 
        Drops = { {Item = "搬運者", Part = "外殼", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "月神", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "機體", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "SARYN", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "S2", 
        Drops = { {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "NOVA", Part = "系統", Rarity = "常見"}, 
                  {Item = "NYX", Part = "系統", Rarity = "罕見"}, 
                  {Item = "帕里斯", Part = "下弓臂", Rarity = "罕見"}, 
                  {Item = "SARYN", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "S3", 
        Drops = { {Item = "月神", Part = "槍管", Rarity = "常見"}, 
                  {Item = "搬運者", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍機", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "瓦斯托", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "旋刃飛刀", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "S5", 
        Drops = { {Item = "拉特昂", Part = "槍機", Rarity = "常見"}, 
                  {Item = "EMBER", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "收割者", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "戰刃", Part = "圓盤", Rarity = "罕見"}, 
                  {Item = "FROST", Part = "系統", Rarity = "罕見"}, 
                  {Item = "暗殺者", Part = "槍機", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "S6", 
        Drops = { {Item = "伯斯頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈扣", Rarity = "罕見"}, 
                  {Item = "席瓦＆神盾", Part = "GUARD", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "S7", 
        Drops = { {Item = "BANSHEE", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "外殼", Rarity = "常見"}, 
                  {Item = "布里斯提卡", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "席芭莉絲", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "席瓦＆神盾", Part = "GUARD", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "中紀", Name = "S8", 
        Drops = { {Item = "野馬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "HYDROID", Part = "機體", Rarity = "常見"}, 
                  {Item = "重擊巨錘", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "旋刃飛刀", Part = "鏢袋", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "T1", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雙短柄戰鐮", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "BANSHEE", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "重擊巨錘", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "V1", 
        Drops = { {Item = "NYX", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雙短柄戰鐮", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "野馬", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "VOLT", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "NOVA", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "V2", 
        Drops = { {Item = "狼牙", Part = "握柄", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "迦倫提恩", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "V3", 
        Drops = { {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "搬運者", Part = "系統", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "頭部神經光元", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "V4", 
        Drops = { {Item = "西諾斯", Part = "弓身", Rarity = "常見"}, 
                  {Item = "猛虎", Part = "槍托", Rarity = "常見"}, 
                  {Item = "野馬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "SARYN", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "ASH", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "凱旋之爪", Part = "拳套", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "V5", 
        Drops = { {Item = "赫利俄斯", Part = "外殼", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "席瓦＆神盾", Part = "握柄", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "伯斯頓", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "頭部神經光元", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "V6", 
        Drops = { {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "弓身", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "重擊巨錘", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "MIRAGE", Part = "系統", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "中紀", Name = "V7", 
        Drops = { {Item = "螺釘雙槍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "食人魚", Part = "槍管", Rarity = "常見"}, 
                  {Item = "BANSHEE", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "西諾斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "中紀", Name = "Z1", 
        Drops = { {Item = "歐特魯斯", Part = "握柄", Rarity = "常見"}, 
                  {Item = "NEKROS", Part = "機體", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "迦倫提恩", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "ZEPHYR", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "A1", 
        Drops = { {Item = "TRINITY", Part = "系統", Rarity = "常見"}, 
                  {Item = "重擊巨錘", Part = "錘頭", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "史提托雙槍", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "雙短柄戰鐮", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "A2", 
        Drops = { {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "雷克斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "雷克斯", Part = "連接器", Rarity = "稀有"}},
        IsBaro = 1},
    { Tier = "後紀", Name = "A3", 
        Drops = { {Item = "布萊頓", Part = "槍管", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "外殼", Rarity = "常見"}, 
                  {Item = "科加基", Part = "靴子", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "弓弦", Rarity = "罕見"}, 
                  {Item = "HYDROID", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "螺釘雙槍", Part = "槍機", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "後紀", Name = "A4", 
        Drops = { {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "ZEPHYR", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "布里斯提卡", Part = "弓弦", Rarity = "罕見"}, 
                  {Item = "狼牙", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "螺釘雙槍", Part = "槍機", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "後紀", Name = "B1", 
        Drops = { {Item = "悅音", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "ASH", Part = "機體", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈扣", Rarity = "罕見"}, 
                  {Item = "BANSHEE", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "B2", 
        Drops = { {Item = "重擊巨錘", Part = "錘頭", Rarity = "常見"}, 
                  {Item = "席芭莉絲", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "歐特魯斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "BANSHEE", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "C1", 
        Drops = { {Item = "TRINITY", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "守望者", Part = "槍管", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "歐特魯斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "西諾斯", Part = "下弓臂", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "C2", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "系統", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "席瓦＆神盾", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "重擊巨錘", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "西諾斯", Part = "下弓臂", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "E1", 
        Drops = { {Item = "拉特昂", Part = "槍管", Rarity = "常見"}, 
                  {Item = "暗殺者", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FROST", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "戰刃", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "EMBER", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "E2", 
        Drops = { {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "野馬", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "悅音", Part = "槍機", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "後紀", Name = "G1", 
        Drops = { {Item = "NEKROS", Part = "機體", Rarity = "常見"}, 
                  {Item = "SARYN", Part = "系統", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈藍圖", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "迦倫提恩", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "H1", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "重擊巨錘", Part = "錘頭", Rarity = "常見"}, 
                  {Item = "守望者", Part = "槍管", Rarity = "常見"}, 
                  {Item = "史提托雙槍", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "TRINITY", Part = "機體", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "頭部", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "H2", 
        Drops = { {Item = "OBERON", Part = "機體", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "握柄", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "機體", Rarity = "罕見"}, 
                  {Item = "史提托雙槍", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "頭部", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "H3", 
        Drops = { {Item = "皇家拐刃", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "弓身", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "外殼", Rarity = "常見"}, 
                  {Item = "伯斯頓", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "HYDROID", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "後紀", Name = "K1", 
        Drops = { {Item = "ODONATA", Part = "外甲", Rarity = "常見"}, 
                  {Item = "飛揚", Part = "鏢袋", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "史提托雙槍", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "喀婆薩庫狛項圈", Part = "項圈扣", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "K2", 
        Drops = { {Item = "歐特魯斯", Part = "握柄", Rarity = "常見"}, 
                  {Item = "席芭莉絲", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"},
                  {Item = "西諾斯", Part = "弓弦", Rarity = "罕見"}, 
                  {Item = "迦倫提恩", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "皇家拐刃", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "K3", 
        Drops = { {Item = "西諾斯", Part = "弓身", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狂鯊", Part = "槍機", Rarity = "常見"}, 
                  {Item = "BANSHEE", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "食人魚", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "皇家拐刃", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "後紀", Name = "L1", 
        Drops = { {Item = "拉特昂", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "收割者", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "蛟龍", Part = "外殼", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "戰刃", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "LOKI", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "L2", 
        Drops = { {Item = "布萊頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "海波斯庫拉對劍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "歐特魯斯", Part = "握柄", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "狂鯊", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "LIMBO", Part = "頭部神經光元", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "後紀", Name = "N1", 
        Drops = { {Item = "布萊頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "史提托雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "ODONATA", Part = "機翼藍圖", Rarity = "罕見"}, 
                  {Item = "ASH", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "N2", 
        Drops = { {Item = "搬運者", Part = "外殼", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "ASH", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "握柄", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "N3", 
        Drops = { {Item = "帕里斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "雙短柄戰鐮", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "VOLT", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "野馬", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "NEKROS", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "N4", 
        Drops = { {Item = "西諾斯", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "NEKROS", Part = "機體", Rarity = "常見"}, 
                  {Item = "重擊巨錘", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "HYDROID", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "NIKANA", Part = "握柄", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "N5", 
        Drops = { {Item = "悅音", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "OBERON", Part = "機體", Rarity = "常見"}, 
                  {Item = "赫利俄斯", Part = "系統", Rarity = "罕見"}, 
                  {Item = "NEKROS", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "海波斯庫拉對劍", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "O1", 
        Drops = { {Item = "悅音", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "史提托雙槍", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "迦倫提恩", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "OBERON", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "O2", 
        Drops = { {Item = "迦倫提恩", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "帕里斯", Part = "弓弦", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "狂鯊", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "赫利俄斯", Part = "系統", Rarity = "罕見"}, 
                  {Item = "OBERON", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "O3", 
        Drops = { {Item = "伯斯頓", Part = "槍托", Rarity = "常見"}, 
                  {Item = "技巧之劍", Part = "握柄", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "凱旋之爪", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "ZEPHYR", Part = "機體", Rarity = "罕見"}, 
                  {Item = "OBERON", Part = "系統", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "後紀", Name = "R1", 
        Drops = { {Item = "螺釘步槍", Part = "槍托", Rarity = "常見"}, 
                  {Item = "MAG", Part = "系統", Rarity = "常見"}, 
                  {Item = "野豬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "達克拉", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "甲龍雙拳", Part = "刀刃", Rarity = "罕見"}, 
                  {Item = "RHINO", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "S1", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "野馬", Part = "槍機", Rarity = "常見"}, 
                  {Item = "野馬", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "野馬雙槍", Part = "連接器", Rarity = "罕見"}, 
                  {Item = "TRINITY", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "分裂斬斧", Part = "刀刃", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "S2", 
        Drops = { {Item = "拉特昂", Part = "槍機", Rarity = "常見"}, 
                  {Item = "LOKI", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "蛟龍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "EMBER", Part = "系統", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "暗殺者", Part = "槍機", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "T1", 
        Drops = { {Item = "守望者", Part = "槍管", Rarity = "常見"}, 
                  {Item = "ODONATA", Part = "外甲", Rarity = "常見"}, 
                  {Item = "SARYN", Part = "系統", Rarity = "常見"}, 
                  {Item = "史提托雙槍", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "伯斯頓", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "藍圖", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "V1", 
        Drops = { {Item = "ODONATA", Part = "系統", Rarity = "常見"}, 
                  {Item = "搬運者", Part = "系統", Rarity = "常見"}, 
                  {Item = "雙短柄戰鐮", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "VOLT", Part = "頭部神經光元", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VAUBAN", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "V2", 
        Drops = { {Item = "飛揚", Part = "鏢袋", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "系統", Rarity = "常見"}, 
                  {Item = "MAG", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "野豬", Part = "槍管", Rarity = "罕見"}, 
                  {Item = "守望者", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "V3", 
        Drops = { {Item = "TRINITY", Part = "頭部神經光元", Rarity = "常見"}, 
                  {Item = "瓦斯托", Part = "槍管", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "系統", Rarity = "常見"}, 
                  {Item = "歐特魯斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "布萊頓", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "守望者", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "V4", 
        Drops = { {Item = "帕里斯", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "TRINITY", Part = "系統", Rarity = "常見"}, 
                  {Item = "ODONATA", Part = "外甲", Rarity = "常見"}, 
                  {Item = "西諾斯", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "守望者", Part = "槍托", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "V5", 
        Drops = { {Item = "凱旋之爪", Part = "刀刃", Rarity = "常見"}, 
                  {Item = "雙短柄戰鐮", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "猛虎", Part = "槍機", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "V6", 
        Drops = { {Item = "布里斯提卡", Part = "下弓臂", Rarity = "常見"}, 
                  {Item = "布萊頓", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "狼牙", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "迦倫提恩", Part = "握柄", Rarity = "罕見"}, 
                  {Item = "VALKYR", Part = "機體", Rarity = "稀有"}},
        IsVaulted = 1},
    { Tier = "後紀", Name = "V7", 
        Drops = { {Item = "雷克斯", Part = "槍管", Rarity = "常見"}, 
                  {Item = "海波斯庫拉對劍", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "VALKYR", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "科加基", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "席瓦＆神盾", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "凱旋之爪", Part = "拳套", Rarity = "稀有"}},
        IsVaulted = 0},
    { Tier = "後紀", Name = "V8", 
        Drops = { {Item = "FORMA", Part = "藍圖", Rarity = "常見"}, 
                  {Item = "雷克斯", Part = "槍機", Rarity = "常見"}, 
                  {Item = "ODONATA", Part = "系統", Rarity = "常見"}, 
                  {Item = "VOLT", Part = "機體", Rarity = "罕見"}, 
                  {Item = "ODONATA", Part = "藍圖", Rarity = "罕見"}, 
                  {Item = "VOLT", Part = "頭部神經光元", Rarity = "稀有"}},
        IsBaro = 1}
    }
}
return VoidData

